- name: copy java to machine
  sudo: yes
  unarchive: src={{java_tar}} dest=/usr/java/

- name: link java
  sudo: yes
  file: src=/usr/java/{{java_untar_floder}} state=link path=/usr/java/default

- name: add to profile
  sudo: yes
  shell: echo 'export JAVA_HOME=/usr/java/default' >> /etc/profile ; echo 'export PATH=$JAVA_HOME/bin:$PATH' >>  /etc/profile 
  
