
- hosts: all
  tasks:
  - { include: "roles/local_repo/tasks/depoly_repo.yml", repo_name: 'cloudera-cdh4' }
  - { include: "roles/local_repo/tasks/depoly_repo.yml", repo_name: 'cloudera-gplextras4' }

- hosts: all
  sudo: yes
  tasks:
  - name: clean yum cache
    shell: yum clean all
