

- name: mkdir tmp dir
  file: path=/tmp/ansible/download state=directory


- name: copy the test data
  copy: src=hadoop-example.jar dest=/tmp/ansible/download/hadoop-example.jar

- name:  test mapreduce pi job
  sudo: yes
  sudo_user: hdfs
  shell: hadoop jar /tmp/ansible/download/hadoop-example.jar pi 3 3

- name: check run success TODO
  shell: hostname
  

