---
# Playbook for  Hadoop master servers

- name: Install the namenode packages
  yum: name={{item}} state=installed
  with_items: 
   - hadoop-hdfs-namenode
   - hadoop-hdfs-zkfc
   - hadoop-lzo-cdh4

- name: Create the data directory for the namenode metadata
  sudo: yes
  file: path={{item}} owner=hdfs group=hdfs state=directory
  with_items: hadoop.dfs_namenode_name_dir 

