
- name: start hive server
  sudo: yes
  script: start.sh

#- name: start hive server
#  sudo: yes
#  service: name=hive-server state=started
#  environment:                                                                     
#    PORT: hive['hive_server_thrift_port']
