
- name: depoly the local repo
  sudo: yes
  template: src={{repo_name}}.repo.j2 dest=/etc/yum.repos.d/{{repo_name}}.repo
  when: local_repo_enabled

- name: depoly the orignal repo
  sudo: yes
  file: src={{repo_name}}.repo dest=/etc/yum.repos.d/{{repo_name}}.repo
  when: not local_repo_enabled     
