
- name: install nginx
  sudo: yes
  yum: name=nginx state=installed


- name: change the nginx's port
  sudo: yes
  shell: sed s#80#{{http_port}}# /etc/nginx/conf.d/default.conf -i 

- name: start nginx
  sudo: yes
  service: name=nginx state=started
