
- name: install nginx
  sudo: yes
  yum: name=nginx stats=installed


- name: change the nginx's port
  sudo: yes
  shell: sudo sed s#80#${port}# /etc/nginx/conf.d/default.conf -i 

- name: start nginx
  sudo: yes
  service: name=nginx start=started
