---

- hosts:
  - NAMENODE[0]
  sudo: yes
  sudo_user: hdfs
  tasks:
  - name: init yarn user directory
    shell: hdfs dfs -mkdir -p {{item}} ; hdfs dfs -chown yarn:yarn {{item}}
    with_items:
     - /user/yarn

  - name: init done dir
    shell: hdfs dfs -mkdir {{item}} ; hdfs dfs -chmod 750 {{item}}
    with_items:
     -  "{{hadoop['mapreduce_jobhistory_done-dir']}}"

  - name: init  intermediate-done-dir dir
    shell: hdfs dfs -mkdir -p {{item}} ;  hdfs dfs -chmod 1777 {{item}}
    with_items:
     -  "{{hadoop['mapreduce_jobhistory_intermediate-done-dir']}}"


  - name: init tmp dir
    shell: hdfs dfs -mkdir -p {{item}} ;  hdfs dfs -chmod 1777 {{item}} 
    with_items: 
     - /tmp

  - name: mkdir log dir
    shell: hdfs dfs -mkdir -p {{item}} ; hdfs dfs -chown yarn:mapred {{item}} ; hdfs dfs -chmod 1777 {{item}}
    with_items:
     - "{{hadoop['yarn_nm_remote-app-log-dir']}}"
