

- hosts: QJM
  tasks:
  - include: roles/qjm/tasks/stop.yml

- hosts: NAMENODE
  tasks:
  - include: roles/namenode/tasks/stop.yml

- hosts: DATANODE
  tasks:
  - include: roles/datanode/tasks/stop.yml

